const sampleReport = {
  id: 163,
  statusReport: 'done',
  complaintNumber: null,
  otherEquipment: null,
  typeActivity: {
    repair: true,
  },
  travelling: [
    {
      origin: {
        location: 'Яна',
        timestamp: '2023-06-22T10:50:00',
      },
      destination: {
        location: 'Мокрище',
        timestamp: '2023-06-22T12:10:00',
      },
      duration: 80,
      vehiclesCount: 1,
      distance: 121.0,
      otherExpenses: '',
      personsParticipated: ['Борис Попов'],
    },
    {
      origin: {
        location: 'Мокрище',
        timestamp: '2023-06-22T17:30:00',
      },
      destination: {
        location: 'Яна',
        timestamp: '2023-06-22T19:00:00',
      },
      duration: 90,
      vehiclesCount: 1,
      distance: 121.0,
      otherExpenses: '',
      personsParticipated: ['Борис Попов'],
    },
  ],
  materials: [
    {
      quantity: 1,
      schemaID: 1,
      schematicLabel: '',
      name: 'Fan - 2GDS25  133X190R',
      itemNumber: null,
      dismantledSerialNumber: '24-16-0092',
      installedSerialNumber: '19-23-0103',
    },
    {
      quantity: 4,
      schemaID: 1,
      schematicLabel: '',
      name: 'filter for fans',
      itemNumber: null,
      dismantledSerialNumber: '',
      installedSerialNumber: '',
    },
  ],
  works: [
    {
      timeWorkStart: {
        location: null,
        timestamp: '2023-06-22T12:10:00',
      },
      timeWorkEnd: {
        location: null,
        timestamp: '2023-06-22T17:10:00',
      },
      workName:
        'Сменен вентилатор на дроселите, проверена обратна връзка за следене на температурите. Сменени филтри на инв.3 и инв.4. Измити външни топлообменници на инв.3 и инв.4',
      personsWorkParticipated: ['Борис Попов'],
    },
  ],
  inverterSerialNumber: null,
  plantName: null,
  customer: '1',
  enumCustomer: [
    {
      display: 'ВЕИ СТРОЙ - ЕАД',
      code: '1',
    },
  ],
  country: 'Bulgaria',
  inverterType: 'S500',
  code: '198',
  display: 'Inverter 4',
  latitude: 42.1735822,
  nodeCode: 198,
  contractNumber: 'CN-00001',
  inverter: '1120162',
  installedPowerMwp: '2.3',
  warrantyStatus: 'Yes',
  deliveryAddress: '84 North Lakeview Road Orchard Park, NY 14127',
  enumInverterNumber: [
    {
      inverterType: 'S500',
      inverter: '1120115',
      code: '123',
      warrantyStatus: 'Yes',
      inverterSerialNumber: '1120115',
      display: 'Inverter 1',
    },
    {
      inverterType: 'S500',
      inverter: '1120106',
      code: '146',
      warrantyStatus: 'Yes',
      inverterSerialNumber: '1120106',
      display: 'Inverter 2',
    },
    {
      inverterType: 'S500',
      inverter: '1120114',
      code: '171',
      warrantyStatus: 'Yes',
      inverterSerialNumber: '1120114',
      display: 'Inverter 3',
    },
    {
      inverterType: 'S500',
      inverter: '1120162',
      code: '198',
      warrantyStatus: 'Yes',
      inverterSerialNumber: '1120162',
      display: 'Inverter 4',
    },
  ],
  plant: 'PV Mokrishte',
  enumPlantName: [
    {
      country: 'Bulgaria',
      code: '3',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '18054513',
          code: '51',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18054513',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '18080006',
          code: '66',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18080006',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '18065966',
          code: '83',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18065966',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '18065965',
          code: '102',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18065965',
          display: 'Inverter 4',
        },
      ],
      display: 'PV Schumen',
      plant: 'PV Schumen',
      latitude: 43.272773,
      installedPowerMwp: '2.3',
      plantName: '3',
      longitude: 26.9845519,
    },
    {
      country: 'Bulgaria',
      code: '10',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '1120115',
          code: '123',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '1120115',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '1120106',
          code: '146',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '1120106',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '1120114',
          code: '171',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '1120114',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '1120162',
          code: '198',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '1120162',
          display: 'Inverter 4',
        },
      ],
      display: 'PV Mokrishte',
      plant: 'PV Mokrishte',
      latitude: 42.1735822,
      installedPowerMwp: '2.3',
      plantName: '10',
      longitude: 24.2946913,
    },
    {
      country: 'Romania',
      code: '17',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '18267174',
          code: '227',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18267174',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '18267175',
          code: '258',
          warrantyStatus: 'Yes',
          inverterSerialNumber: '18267175',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Craiova',
      plant: 'PV Craiova',
      latitude: 44.439965,
      installedPowerMwp: '1',
      plantName: '17',
      longitude: 23.6927853,
    },
    {
      country: 'Bulgaria',
      code: '26',
      enumInverterNumber: [
        {
          inverterType: 'S250',
          inverter: '20943030',
          code: '291',
          warrantyStatus: 'No',
          inverterSerialNumber: '20943030',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S250',
          inverter: '3940430',
          code: '326',
          warrantyStatus: 'No',
          inverterSerialNumber: '3940430',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S250',
          inverter: '18111031',
          code: '363',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111031',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S250',
          inverter: '17862550',
          code: '402',
          warrantyStatus: 'No',
          inverterSerialNumber: '17862550',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S250',
          inverter: '18123743',
          code: '443',
          warrantyStatus: 'No',
          inverterSerialNumber: '18123743',
          display: 'Inverter 5',
        },
        {
          inverterType: 'S250',
          inverter: '18123746',
          code: '486',
          warrantyStatus: 'No',
          inverterSerialNumber: '18123746',
          display: 'Inverter 6',
        },
        {
          inverterType: 'S250',
          inverter: '18183521',
          code: '578',
          warrantyStatus: 'No',
          inverterSerialNumber: '18183521',
          display: 'Inverter 7',
        },
        {
          inverterType: 'S250',
          inverter: '18152982',
          code: '627',
          warrantyStatus: 'No',
          inverterSerialNumber: '18152982',
          display: 'Inverter 8',
        },
        {
          inverterType: 'S250',
          inverter: '18111029',
          code: '678',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111029',
          display: 'Inverter 9',
        },
        {
          inverterType: 'S250',
          inverter: '18082049',
          code: '731',
          warrantyStatus: 'No',
          inverterSerialNumber: '18082049',
          display: 'Inverter 10',
        },
        {
          inverterType: 'S250',
          inverter: '18183523',
          code: '786',
          warrantyStatus: 'No',
          inverterSerialNumber: '18183523',
          display: 'Inverter 11',
        },
        {
          inverterType: 'S250',
          inverter: '18183522',
          code: '1523',
          warrantyStatus: 'No',
          inverterSerialNumber: '18183522',
          display: 'Inverter 12',
        },
        {
          inverterType: 'S250',
          inverter: '18183524',
          code: '902',
          warrantyStatus: 'No',
          inverterSerialNumber: '18183524',
          display: 'Inverter 13',
        },
        {
          inverterType: 'S250',
          inverter: '18152990',
          code: '963',
          warrantyStatus: 'No',
          inverterSerialNumber: '18152990',
          display: 'Inverter 14',
        },
        {
          inverterType: 'S250',
          inverter: '18111027',
          code: '1091',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111027',
          display: 'Inverter 15',
        },
        {
          inverterType: 'S250',
          inverter: '18111030',
          code: '1026',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111030',
          display: 'Inverter 16',
        },
        {
          inverterType: 'S250',
          inverter: '17849764',
          code: '1158',
          warrantyStatus: 'No',
          inverterSerialNumber: '17849764',
          display: 'Inverter 17',
        },
        {
          inverterType: 'S250',
          inverter: '18111032',
          code: '843',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111032',
          display: 'Inverter 18',
        },
      ],
      display: 'PV Detelini',
      plant: 'PV Detelini',
      latitude: 41.785694,
      installedPowerMwp: '4.5',
      plantName: '26',
      longitude: 25.662458,
    },
    {
      country: 'Bulgaria',
      code: '37',
      enumInverterNumber: [
        {
          inverterType: 'S250',
          inverter: '18123745',
          code: '1298',
          warrantyStatus: 'No',
          inverterSerialNumber: '18123745',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S250',
          inverter: '18123748',
          code: '1227',
          warrantyStatus: 'No',
          inverterSerialNumber: '18123748',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S250',
          inverter: '18183520',
          code: '1371',
          warrantyStatus: 'No',
          inverterSerialNumber: '18183520',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S250',
          inverter: '18111028',
          code: '1446',
          warrantyStatus: 'No',
          inverterSerialNumber: '18111028',
          display: 'Inverter 4',
        },
      ],
      display: 'PV \tNITC-Stambolovo',
      plant: 'PV \tNITC-Stambolovo',
      latitude: 41.785694,
      installedPowerMwp: '1',
      plantName: '37',
      longitude: 25.662458,
    },
    {
      country: 'Bulgaria',
      code: '50',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '29843903',
          code: '18498',
          warrantyStatus: 'No',
          inverterSerialNumber: '29843903',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '4404',
          code: '21906',
          warrantyStatus: 'No',
          inverterSerialNumber: '4404',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '28563',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '1122332',
          code: '29243',
          warrantyStatus: 'No',
          inverterSerialNumber: '1122332',
          display: 'Inverter 4',
        },
      ],
      display: 'PV ESP32',
      plant: 'PV ESP32',
      latitude: 43.272773,
      installedPowerMwp: '1',
      plantName: '50',
      longitude: 26.9845519,
    },
    {
      country: 'Bulgaria',
      code: '65',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11-20013',
          code: '1602',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-20013',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '11-20014',
          code: '1683',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-20014',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Rakovskovo-1A',
      plant: 'PV Rakovskovo-1A',
      latitude: 42.828139,
      installedPowerMwp: '1',
      plantName: '65',
      longitude: 27.763115,
    },
    {
      country: 'Bulgaria',
      code: '82',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11-20012',
          code: '1766',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-20012',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '11-20015',
          code: '1851',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-20015',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Rakovskovo-1B',
      plant: 'PV Rakovskovo-1B',
      latitude: 42.828139,
      installedPowerMwp: '1',
      plantName: '82',
      longitude: 27.763115,
    },
    {
      country: 'Bulgaria',
      code: '101',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '17847752',
          code: '1938',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847752',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '17847749',
          code: '2027',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847749',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Vinarsko',
      plant: 'PV Vinarsko',
      latitude: 42.540162,
      installedPowerMwp: '1',
      plantName: '101',
      longitude: 27.302808,
    },
    {
      country: 'Bulgaria',
      code: '122',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '18191136',
          code: '2118',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191136',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '17847753',
          code: '2211',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847753',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '18191137',
          code: '2403',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191137',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S500',
          inverter: '18191138',
          code: '2603',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191138',
          display: 'Inverter 6',
        },
        {
          inverterType: 'S500',
          inverter: '18191142',
          code: '2706',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191142',
          display: 'Inverter 7',
        },
        {
          inverterType: 'S500',
          inverter: '18191139',
          code: '2811',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191139',
          display: 'Inverter 8',
        },
      ],
      display: 'PV Cherni Vrah',
      plant: 'PV Cherni Vrah',
      latitude: 42.45536,
      installedPowerMwp: '3',
      plantName: '122',
      longitude: 27.327212,
    },
    {
      country: 'Bulgaria',
      code: '145',
      enumInverterNumber: [
        {
          inverterType: 'S100',
          inverter: '20304950',
          code: '3251',
          warrantyStatus: 'No',
          inverterSerialNumber: '20304950',
          display: 'Inverter 1',
        },
      ],
      display: 'PV Koprivlen',
      plant: 'PV Koprivlen',
      latitude: 41.51555,
      installedPowerMwp: '0.1',
      plantName: '145',
      longitude: 23.802081,
    },
    {
      country: 'Bulgaria',
      code: '170',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '17775214',
          code: '3366',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775214',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '17775215',
          code: '4491',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775215',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '17775212',
          code: '4626',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775212',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '17775213',
          code: '4763',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775213',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S500',
          inverter: '18191144',
          code: '5043',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191144',
          display: 'Inverter 5',
        },
        {
          inverterType: 'S500',
          inverter: '18191141',
          code: '4902',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191141',
          display: 'Inverter 6',
        },
        {
          inverterType: 'S500',
          inverter: '?????',
          code: '28902',
          warrantyStatus: 'No',
          inverterSerialNumber: '?????',
          display: 'Inverter 7',
        },
        {
          inverterType: 'S500',
          inverter: '18205443',
          code: '5186',
          warrantyStatus: 'No',
          inverterSerialNumber: '18205443',
          display: 'Inverter 8',
        },
        {
          inverterType: 'S500',
          inverter: '18191147',
          code: '5331',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191147',
          display: 'Inverter 9',
        },
        {
          inverterType: 'S500',
          inverter: '18205412',
          code: '5478',
          warrantyStatus: 'No',
          inverterSerialNumber: '18205412',
          display: 'Inverter 10',
        },
      ],
      display: 'PV Milkovitsa',
      plant: 'PV Milkovitsa',
      latitude: 43.626226,
      installedPowerMwp: '4.5',
      plantName: '170',
      longitude: 24.725638,
    },
    {
      country: 'Bulgaria',
      code: '197',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '17847751',
          code: '3723',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847751',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '17847750',
          code: '3602',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847750',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S500',
          inverter: '17847748',
          code: '3846',
          warrantyStatus: 'No',
          inverterSerialNumber: '17847748',
          display: 'Inverter 5',
        },
        {
          inverterType: 'S500',
          inverter: '17775217',
          code: '3971',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775217',
          display: 'Inverter 6',
        },
        {
          inverterType: 'S500',
          inverter: '17775216',
          code: '4098',
          warrantyStatus: 'No',
          inverterSerialNumber: '17775216',
          display: 'Inverter 7',
        },
      ],
      display: 'PV Boynitsa',
      plant: 'PV Boynitsa',
      latitude: 43.964085,
      installedPowerMwp: '3',
      plantName: '197',
      longitude: 22.536793,
    },
    {
      country: 'Bulgaria',
      code: '226',
      enumInverterNumber: [
        {
          inverterType: 'S250',
          inverter: '222',
          code: '4227',
          warrantyStatus: 'No',
          inverterSerialNumber: '222',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S250',
          inverter: '222',
          code: '4358',
          warrantyStatus: 'No',
          inverterSerialNumber: '222',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Smirnenski',
      plant: 'PV Smirnenski',
      latitude: 43.752024,
      installedPowerMwp: '1',
      plantName: '226',
      longitude: 26.299659,
    },
    {
      country: 'Switzerland',
      code: '290',
      enumInverterNumber: [
        {
          inverterType: 'S200',
          inverter: '17796508',
          code: '5778',
          warrantyStatus: 'No',
          inverterSerialNumber: '17796508',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S200',
          inverter: '17796507',
          code: '5931',
          warrantyStatus: 'No',
          inverterSerialNumber: '17796507',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Migros San Antonino',
      plant: 'PV Migros San Antonino',
      latitude: 46.155179,
      installedPowerMwp: '0.4',
      plantName: '290',
      longitude: 8.959713,
    },
    {
      country: 'Bulgaria',
      code: '325',
      enumInverterNumber: [
        {
          inverterType: 'S250',
          inverter: '22222',
          code: '6243',
          warrantyStatus: 'No',
          inverterSerialNumber: '22222',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S250',
          inverter: '11111',
          code: '6086',
          warrantyStatus: 'No',
          inverterSerialNumber: '11111',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S250',
          inverter: '33333',
          code: '6402',
          warrantyStatus: 'No',
          inverterSerialNumber: '33333',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S250',
          inverter: '4444',
          code: '6563',
          warrantyStatus: 'No',
          inverterSerialNumber: '4444',
          display: 'Inverter 4',
        },
      ],
      display: 'PV Lom',
      plant: 'PV Lom',
      latitude: 43.790799,
      installedPowerMwp: '5',
      plantName: '325',
      longitude: 23.231392,
    },
    {
      country: 'Bulgaria',
      code: '362',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '1111',
          code: '6891',
          warrantyStatus: 'No',
          inverterSerialNumber: '1111',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '2222',
          code: '7058',
          warrantyStatus: 'No',
          inverterSerialNumber: '2222',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Boynitsa(1-2)',
      plant: 'PV Boynitsa(1-2)',
      latitude: 43.964085,
      installedPowerMwp: '1',
      plantName: '362',
      longitude: 22.536793,
    },
    {
      country: 'Bulgaria',
      code: '401',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '17894673',
          code: '7398',
          warrantyStatus: 'No',
          inverterSerialNumber: '17894673',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '17894674',
          code: '7571',
          warrantyStatus: 'No',
          inverterSerialNumber: '17894674',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '17894672',
          code: '7746',
          warrantyStatus: 'No',
          inverterSerialNumber: '17894672',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '17894675',
          code: '7923',
          warrantyStatus: 'No',
          inverterSerialNumber: '17894675',
          display: 'Inverter 4',
        },
      ],
      display: 'PV Orlova Mogila',
      plant: 'PV Orlova Mogila',
      latitude: 43.964085,
      installedPowerMwp: '2',
      plantName: '401',
      longitude: 22.536793,
    },
    {
      country: 'Turkey',
      code: '442',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '220007',
          code: '8102',
          warrantyStatus: 'No',
          inverterSerialNumber: '220007',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '210054',
          code: '8283',
          warrantyStatus: 'No',
          inverterSerialNumber: '210054',
          display: 'Inverter 2',
        },
      ],
      display: 'KARAMAN CBC KİSECİK',
      plant: 'KARAMAN CBC KİSECİK',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '442',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '485',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '210070',
          code: '8466',
          warrantyStatus: 'No',
          inverterSerialNumber: '210070',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '210052\r\n',
          code: '8651',
          warrantyStatus: 'No',
          inverterSerialNumber: '210052\r\n',
          display: 'Inverter 2',
        },
      ],
      display: 'KARAMAN SEG AKDENİZ',
      plant: 'KARAMAN SEG AKDENİZ',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '485',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '530',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '210064\r\n',
          code: '8838',
          warrantyStatus: 'No',
          inverterSerialNumber: '210064\r\n',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '210114\r\n',
          code: '9027',
          warrantyStatus: 'No',
          inverterSerialNumber: '210114\r\n',
          display: 'Inverter 2',
        },
      ],
      display: 'KARAMAN SEG EGE GES',
      plant: 'KARAMAN SEG EGE GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '530',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '577',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '',
          code: '9218',
          warrantyStatus: 'no',
          inverterSerialNumber: '',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '',
          code: '9411',
          warrantyStatus: 'No',
          inverterSerialNumber: '',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY AKSARAY GES',
      plant: 'AKSARAY AKSARAY GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '577',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '626',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '1234',
          code: '9606',
          warrantyStatus: 'No',
          inverterSerialNumber: '1234',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '1234',
          code: '9803',
          warrantyStatus: 'No',
          inverterSerialNumber: '1234',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY ALANYA GES',
      plant: 'AKSARAY ALANYA GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '626',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '677',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '8383',
          code: '10002',
          warrantyStatus: 'No',
          inverterSerialNumber: '8383',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '2232',
          code: '10203',
          warrantyStatus: 'No',
          inverterSerialNumber: '2232',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY ANADOLU GES',
      plant: 'AKSARAY ANADOLU GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '677',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '785',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '22232',
          code: '10818',
          warrantyStatus: 'No',
          inverterSerialNumber: '22232',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '222222',
          code: '11027',
          warrantyStatus: 'No',
          inverterSerialNumber: '222222',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY ESKIL GES',
      plant: 'AKSARAY ESKIL GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '785',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '842',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '2838383',
          code: '11238',
          warrantyStatus: 'No',
          inverterSerialNumber: '2838383',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '222222',
          code: '11451',
          warrantyStatus: 'No',
          inverterSerialNumber: '222222',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY KARADENİZ GES',
      plant: 'AKSARAY KARADENİZ GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '842',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '901',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '2222222',
          code: '11666',
          warrantyStatus: 'No',
          inverterSerialNumber: '2222222',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '22222222',
          code: '11883',
          warrantyStatus: 'No',
          inverterSerialNumber: '22222222',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY KAVAKLI GES',
      plant: 'AKSARAY KAVAKLI GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '901',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '962',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '22222222',
          code: '12102',
          warrantyStatus: 'No',
          inverterSerialNumber: '22222222',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '2222222',
          code: '12323',
          warrantyStatus: 'No',
          inverterSerialNumber: '2222222',
          display: 'Inverter 2',
        },
      ],
      display: 'AKSARAY MİLAS GES',
      plant: 'AKSARAY MİLAS GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '962',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1025',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11111',
          code: '12546',
          warrantyStatus: 'No',
          inverterSerialNumber: '11111',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '12234',
          code: '12771',
          warrantyStatus: 'No',
          inverterSerialNumber: '12234',
          display: 'Inverter 2',
        },
      ],
      display: 'URFA ENES GES',
      plant: 'URFA ENES GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1025',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1090',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '893748',
          code: '12998',
          warrantyStatus: 'No',
          inverterSerialNumber: '893748',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '3298393',
          code: '13227',
          warrantyStatus: 'No',
          inverterSerialNumber: '3298393',
          display: 'Inverter 2',
        },
      ],
      display: 'URFA MERVE GES',
      plant: 'URFA MERVE GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1090',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1157',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '2398933',
          code: '13458',
          warrantyStatus: 'No',
          inverterSerialNumber: '2398933',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '289393',
          code: '13691',
          warrantyStatus: 'No',
          inverterSerialNumber: '289393',
          display: 'Inverter 2',
        },
      ],
      display: 'URFA ASLAN GES',
      plant: 'URFA ASLAN GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1157',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1226',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '298393',
          code: '13926',
          warrantyStatus: 'No',
          inverterSerialNumber: '298393',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '289393',
          code: '14163',
          warrantyStatus: 'No',
          inverterSerialNumber: '289393',
          display: 'Inverter 2',
        },
      ],
      display: 'URFA NUR GES',
      plant: 'URFA NUR GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1226',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1297',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '2838383',
          code: '14402',
          warrantyStatus: 'No',
          inverterSerialNumber: '2838383',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '2838383',
          code: '14643',
          warrantyStatus: 'No',
          inverterSerialNumber: '2838383',
          display: 'Inverter 2',
        },
      ],
      display: 'NIGDE SUDEGE GES',
      plant: 'NIGDE SUDEGE GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1297',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1370',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '288383',
          code: '14886',
          warrantyStatus: 'No',
          inverterSerialNumber: '288383',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '2838493',
          code: '15131',
          warrantyStatus: 'No',
          inverterSerialNumber: '2838493',
          display: 'Inverter 2',
        },
      ],
      display: 'NIGDE EKO-4 GES\r\n',
      plant: 'NIGDE EKO-4 GES\r\n',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1370',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1445',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '292922',
          code: '15378',
          warrantyStatus: 'No',
          inverterSerialNumber: '292922',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '283838',
          code: '15627',
          warrantyStatus: 'No',
          inverterSerialNumber: '283838',
          display: 'Inverter 2',
        },
      ],
      display: 'NIGDE SARP-1 GES',
      plant: 'NIGDE SARP-1 GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1445',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1522',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '3848591',
          code: '15878',
          warrantyStatus: 'No',
          inverterSerialNumber: '3848591',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '3847492',
          code: '16131',
          warrantyStatus: 'No',
          inverterSerialNumber: '3847492',
          display: 'Inverter 2',
        },
      ],
      display: 'NIGDE NAZ-1',
      plant: 'NIGDE NAZ-1',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1522',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1601',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '38484720',
          code: '16386',
          warrantyStatus: 'No',
          inverterSerialNumber: '38484720',
          display: 'Inverter 1',
        },
      ],
      display: 'KAYSERİ-SMART GES',
      plant: 'KAYSERİ-SMART GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1601',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1682',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '28375949',
          code: '16643',
          warrantyStatus: 'No',
          inverterSerialNumber: '28375949',
          display: 'Inverter 1',
        },
      ],
      display: 'KAYSERİ-GBI GES',
      plant: 'KAYSERİ-GBI GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1682',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1765',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '284848593',
          code: '16902',
          warrantyStatus: 'No',
          inverterSerialNumber: '284848593',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '394958302',
          code: '17163',
          warrantyStatus: 'No',
          inverterSerialNumber: '394958302',
          display: 'Inverter 2',
        },
      ],
      display: 'KAYSERİ-EGE GES',
      plant: 'KAYSERİ-EGE GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1765',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1850',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '38458393',
          code: '17426',
          warrantyStatus: 'No',
          inverterSerialNumber: '38458393',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '839485093',
          code: '17691',
          warrantyStatus: 'No',
          inverterSerialNumber: '839485093',
          display: 'Inverter 2',
        },
      ],
      display: 'KAYSERİ CPN GES',
      plant: 'KAYSERİ CPN GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1850',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '1937',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '384889',
          code: '17958',
          warrantyStatus: 'No',
          inverterSerialNumber: '384889',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '24383840',
          code: '18227',
          warrantyStatus: 'No',
          inverterSerialNumber: '24383840',
          display: 'Inverter 2',
        },
      ],
      display: 'KAYSERI EFMC GES',
      plant: 'KAYSERI EFMC GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '1937',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '2026',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '3949585839',
          code: '19323',
          warrantyStatus: 'No',
          inverterSerialNumber: '3949585839',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '348509659',
          code: '19602',
          warrantyStatus: 'No',
          inverterSerialNumber: '348509659',
          display: 'Inverter 2',
        },
      ],
      display: 'ELAZIĞ\r\n\r\n ELAZIĞ GES',
      plant: 'ELAZIĞ\r\n\r\n ELAZIĞ GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '2026',
      longitude: 28.97953,
    },
    {
      country: 'Turkey',
      code: '2117',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '283948492',
          code: '18771',
          warrantyStatus: 'No',
          inverterSerialNumber: '283948492',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '3432432432',
          code: '19046',
          warrantyStatus: 'No',
          inverterSerialNumber: '3432432432',
          display: 'Inverter 2',
        },
      ],
      display: 'ELAZIĞ Hayran GES',
      plant: 'ELAZIĞ Hayran GES',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '2117',
      longitude: 28.97953,
    },
    {
      country: 'Bulgaria',
      code: '2210',
      enumInverterNumber: [
        {
          inverterType: 'S250',
          inverter: '2222',
          code: '23106',
          warrantyStatus: 'No',
          inverterSerialNumber: '2222',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S250',
          inverter: '11-20037',
          code: '22203',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-20037',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S250',
          inverter: '22222',
          code: '22502',
          warrantyStatus: 'No',
          inverterSerialNumber: '22222',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S250',
          inverter: '2222',
          code: '22803',
          warrantyStatus: 'No',
          inverterSerialNumber: '2222',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S250',
          inverter: '222',
          code: '23411',
          warrantyStatus: 'No',
          inverterSerialNumber: '222',
          display: 'Inverter 5',
        },
        {
          inverterType: 'S250',
          inverter: '338',
          code: '23718',
          warrantyStatus: 'No',
          inverterSerialNumber: '338',
          display: 'Inverter 6',
        },
      ],
      display: 'PV Pastrogor',
      plant: 'PV Pastrogor',
      latitude: 41.015137,
      installedPowerMwp: '1',
      plantName: '2210',
      longitude: 28.97953,
    },
    {
      country: 'Bulgaria',
      code: '2402',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11-200xx',
          code: '24966',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200xx',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '11-200xx',
          code: '24027',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200xx',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Strazhica',
      plant: 'PV Strazhica',
      latitude: 43.626226,
      installedPowerMwp: '1',
      plantName: '2402',
      longitude: 27.302808,
    },
    {
      country: 'Bulgaria',
      code: '2501',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '26571',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '26898',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '11-201xx',
          code: '24651',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-201xx',
          display: 'Inverter 3',
        },
        {
          inverterType: 'S500',
          inverter: '11-200xx',
          code: '24338',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200xx',
          display: 'Inverter 4',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '25283',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 5',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '25602',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 6',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '25923',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 7',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '26246',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 8',
        },
      ],
      display: 'PV Lovech',
      plant: 'PV Lovech',
      latitude: 43.626226,
      installedPowerMwp: '5',
      plantName: '2501',
      longitude: 27.302808,
    },
    {
      country: 'Italy',
      code: '2602',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '27891',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '11-200x',
          code: '28226',
          warrantyStatus: 'No',
          inverterSerialNumber: '11-200x',
          display: 'Inverter 2',
        },
      ],
      display: 'PV Romeo11',
      plant: 'PV Romeo11',
      latitude: 39.404,
      installedPowerMwp: '1',
      plantName: '2602',
      longitude: 23.40404,
    },
    {
      country: 'Romaina',
      code: '2705',
      enumInverterNumber: [
        {
          inverterType: 'S500',
          inverter: '18205412',
          code: '29586',
          warrantyStatus: 'No',
          inverterSerialNumber: '18205412',
          display: 'Inverter 1',
        },
        {
          inverterType: 'S500',
          inverter: '18205413',
          code: '30278',
          warrantyStatus: 'No',
          inverterSerialNumber: '18205413',
          display: 'Inverter 2',
        },
        {
          inverterType: 'S500',
          inverter: '18191146',
          code: '29931',
          warrantyStatus: 'No',
          inverterSerialNumber: '18191146',
          display: 'Inverter 3',
        },
      ],
      display: 'PV Slobozia2',
      plant: 'PV Slobozia2',
      latitude: 43.626226,
      installedPowerMwp: '1.5',
      plantName: '2705',
      longitude: 27.302808,
    },
  ],
  serviceOperator: 'Convesys',
  inverterSerialNumber: '1120162',
  plantName: '10',
  longitude: 24.2946913,
};
