// TODO: load from backend
export const inverterSchemas = [
  {
    id: 1,
    description: 'SOLO 500',
    name: 'ISC-33-114-V1.01-R05',
    version: '1.01',
    status: 'production',
    dateModified: '2012-04-19',
    materials: [
      {
        id: 1,
        name: 'POWER SUPPLY - TRIO-PS/1AC/24DC/2,5',
        schematicLabel: '25K1',
        itemNumber: '2352',
      },
      {
        id: 5,
        name: 'UFB40 R0.3',
        schematicLabel: '10A1',
        itemNumber: null,
      },
      {
        id: 6,
        name: 'Voltage feedback board - UFB40 R0.3',
        schematicLabel: '10A1',
        itemNumber: null,
      },
      {
        id: 7,
        name: 'Voltage feedback board - UFB40 R0.3',
        schematicLabel: '10A2',
        itemNumber: null,
      },
      {
        id: 8,
        name: 'Voltage feedback board - UFB40 R0.3',
        schematicLabel: '10A3',
        itemNumber: null,
      },
      {
        id: 9,
        name: 'Voltage feedback board - UFB40 R0.3',
        schematicLabel: '11A1',
        itemNumber: null,
      },
      {
        id: 10,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F1',
        itemNumber: null,
      },
      {
        id: 11,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F2',
        itemNumber: null,
      },
      {
        id: 12,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F3',
        itemNumber: null,
      },
      {
        id: 13,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F4',
        itemNumber: null,
      },
      {
        id: 14,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F5',
        itemNumber: null,
      },
      {
        id: 15,
        name: 'Fuse Holder - PCF 10 DC',
        schematicLabel: '10F6',
        itemNumber: null,
      },
      {
        id: 16,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F1',
        itemNumber: null,
      },
      {
        id: 17,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F2',
        itemNumber: null,
      },
      {
        id: 18,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F3',
        itemNumber: null,
      },
      {
        id: 19,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F4',
        itemNumber: null,
      },
      {
        id: 20,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F5',
        itemNumber: null,
      },
      {
        id: 21,
        name: 'Fuse - CH10x38 PV 2 A',
        schematicLabel: '10F6',
        itemNumber: null,
      },
      {
        id: 22,
        name: 'Surge arrester - DEHNguard M YPV SCI 1200FM',
        schematicLabel: '10R1',
        itemNumber: null,
      },
      {
        id: 23,
        name: 'Surge arrester - DEHNguard M YPV SCI 1200FM',
        schematicLabel: '10R2',
        itemNumber: null,
      },
      {
        id: 24,
        name: 'Surge arrester - DEHNguard M YPV SCI 1200FM',
        schematicLabel: '10R3',
        itemNumber: null,
      },
      {
        id: 25,
        name: 'Wiring bridge for modules  - MPB 18/1-57 ',
        schematicLabel: '10R1',
        itemNumber: null,
      },
      {
        id: 26,
        name: 'Wiring bridge for modules  - MPB 18/1-57 ',
        schematicLabel: '10R2',
        itemNumber: null,
      },
      {
        id: 27,
        name: 'Wiring bridge for modules  - MPB 18/1-57 ',
        schematicLabel: '10R3',
        itemNumber: null,
      },
      {
        id: 28,
        name: 'Current sensor - LF 505-S',
        schematicLabel: '10T1',
        itemNumber: null,
      },
      {
        id: 29,
        name: 'Current sensor - LF 505-S',
        schematicLabel: '10T2',
        itemNumber: null,
      },
      {
        id: 30,
        name: 'Current sensor - LF 505-S',
        schematicLabel: '10T3',
        itemNumber: null,
      },
      {
        id: 31,
        name: 'DC-EMV-Filter PV - 2F1000-1000.260',
        schematicLabel: '10Z1',
        itemNumber: null,
      },
      {
        id: 32,
        name: 'C-bank Solo 500 - C-69-4320-2.0',
        schematicLabel: '11C1',
        itemNumber: null,
      },
      {
        id: 33,
        name: 'Strain relief black - AC 166-1/3 ZEL RH',
        schematicLabel: '11C1',
        itemNumber: null,
      },
      {
        id: 34,
        name: 'Cable socket black - AC 166 GBU/ 3 BLACK',
        schematicLabel: '11C1',
        itemNumber: null,
      },
      {
        id: 35,
        name: 'PU Solo 500 - IPU-69-20-1.0',
        schematicLabel: '11V1',
        itemNumber: null,
      },
      {
        id: 36,
        name: 'Voltage feedback board - UFB40 R0.2',
        schematicLabel: '12A3',
        itemNumber: null,
      },
      {
        id: 37,
        name: 'Voltage feedback board - UFB40 R0.2',
        schematicLabel: '12A4',
        itemNumber: null,
      },
      {
        id: 38,
        name: 'Rectifier for precharge - PSD 62/18',
        schematicLabel: '12A5',
        itemNumber: null,
      },
      {
        id: 39,
        name: 'Capacitor for sinusoidal filter -',
        schematicLabel: '12C1',
        itemNumber: null,
      },
      {
        id: 40,
        name: 'Capacitor for sinusoidal filter -',
        schematicLabel: '12C2',
        itemNumber: null,
      },
      {
        id: 41,
        name: 'Capacitor for sinusoidal filter -',
        schematicLabel: '12C3',
        itemNumber: null,
      },
      {
        id: 42,
        name: 'Capacitor for precharge filter - RBPS 22496KC7JZZ',
        schematicLabel: '12C4',
        itemNumber: null,
      },
      {
        id: 43,
        name: 'Switch-disconnector - LZMN4-AE1600-I',
        schematicLabel: '12F1',
        itemNumber: null,
      },
      {
        id: 44,
        name: 'Door coupling rotary handle - NZM4-XTVD',
        schematicLabel: '12F1',
        itemNumber: null,
      },
      {
        id: 45,
        name: 'Extension shaft - NZM3/4-XV4',
        schematicLabel: '12F1',
        itemNumber: null,
      },
      {
        id: 46,
        name: 'Make contact Front - M22-K10',
        schematicLabel: '12F1',
        itemNumber: null,
      },
      {
        id: 47,
        name: 'Break contact Front - M22-K01',
        schematicLabel: '12F1',
        itemNumber: null,
      },
      {
        id: 48,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F2',
        itemNumber: null,
      },
      {
        id: 49,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F3',
        itemNumber: null,
      },
      {
        id: 50,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F4',
        itemNumber: null,
      },
      {
        id: 51,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F5',
        itemNumber: null,
      },
      {
        id: 52,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F6',
        itemNumber: null,
      },
      {
        id: 53,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '12F7',
        itemNumber: null,
      },
      {
        id: 54,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '25F1',
        itemNumber: null,
      },
      {
        id: 55,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '25F2',
        itemNumber: null,
      },
      {
        id: 56,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '25F3',
        itemNumber: null,
      },
      {
        id: 57,
        name: 'Fuse terminal block - WAGO  282-128',
        schematicLabel: '25F5',
        itemNumber: null,
      },
      {
        id: 58,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F2',
        itemNumber: null,
      },
      {
        id: 59,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F3',
        itemNumber: null,
      },
      {
        id: 60,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F4',
        itemNumber: null,
      },
      {
        id: 61,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F5',
        itemNumber: null,
      },
      {
        id: 62,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F6',
        itemNumber: null,
      },
      {
        id: 63,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '12F7',
        itemNumber: null,
      },
      {
        id: 64,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '25F1',
        itemNumber: null,
      },
      {
        id: 65,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '25F2',
        itemNumber: null,
      },
      {
        id: 66,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '25F3',
        itemNumber: null,
      },
      {
        id: 67,
        name: 'End and intern. Plate/grey - 282-311',
        schematicLabel: '25F5',
        itemNumber: null,
      },
      {
        id: 68,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F2',
        itemNumber: null,
      },
      {
        id: 69,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F3',
        itemNumber: null,
      },
      {
        id: 70,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F4',
        itemNumber: null,
      },
      {
        id: 71,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F5',
        itemNumber: null,
      },
      {
        id: 72,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F6',
        itemNumber: null,
      },
      {
        id: 73,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '12F7',
        itemNumber: null,
      },
      {
        id: 74,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '25F1',
        itemNumber: null,
      },
      {
        id: 75,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '25F2',
        itemNumber: null,
      },
      {
        id: 76,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '25F3',
        itemNumber: null,
      },
      {
        id: 77,
        name: 'RL MTD INS ADJ JUMPER - 282-402',
        schematicLabel: '25F5',
        itemNumber: null,
      },
      {
        id: 78,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F2',
        itemNumber: null,
      },
      {
        id: 79,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F3',
        itemNumber: null,
      },
      {
        id: 80,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F4',
        itemNumber: null,
      },
      {
        id: 81,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F5',
        itemNumber: null,
      },
      {
        id: 82,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F6',
        itemNumber: null,
      },
      {
        id: 83,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '12F7',
        itemNumber: null,
      },
      {
        id: 84,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '25F1',
        itemNumber: null,
      },
      {
        id: 85,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '25F2',
        itemNumber: null,
      },
      {
        id: 86,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '25F3',
        itemNumber: null,
      },
      {
        id: 87,
        name: 'Fuse - SPT 0001.2531',
        schematicLabel: '25F5',
        itemNumber: null,
      },
      {
        id: 88,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F2',
        itemNumber: null,
      },
      {
        id: 89,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F3',
        itemNumber: null,
      },
      {
        id: 90,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F4',
        itemNumber: null,
      },
      {
        id: 91,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F5',
        itemNumber: null,
      },
      {
        id: 92,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F6',
        itemNumber: null,
      },
      {
        id: 93,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '12F7',
        itemNumber: null,
      },
      {
        id: 94,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '25F1',
        itemNumber: null,
      },
      {
        id: 95,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '25F2',
        itemNumber: null,
      },
      {
        id: 96,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '25F3',
        itemNumber: null,
      },
      {
        id: 97,
        name: 'Fuse - SPT 0001.2521',
        schematicLabel: '25F5',
        itemNumber: null,
      },
      {
        id: 98,
        name: 'Contactor - A 9-30-10 230VAC',
        schematicLabel: '12K1',
        itemNumber: null,
      },
      {
        id: 99,
        name: 'Contactor - A 9-30-10 230VAC',
        schematicLabel: '25K3',
        itemNumber: null,
      },
      {
        id: 100,
        name: 'Surge suppressor - RC 5-1/250',
        schematicLabel: '12K1',
        itemNumber: null,
      },
      {
        id: 101,
        name: 'Surge suppressor - RC 5-1/250',
        schematicLabel: '25K3',
        itemNumber: null,
      },
      {
        id: 102,
        name: 'AC Line inductor - DX-Drossel',
        schematicLabel: '12L1',
        itemNumber: null,
      },
      {
        id: 103,
        name: 'AC Line inductor - DX-Drossel',
        schematicLabel: '12L2',
        itemNumber: null,
      },
      {
        id: 104,
        name: 'Water Resistor - 150A 3 x 2000 W',
        schematicLabel: '12R1',
        itemNumber: null,
      },
      {
        id: 105,
        name: 'Resistors - 47R / 150W',
        schematicLabel: '12R2',
        itemNumber: null,
      },
      {
        id: 106,
        name: 'Resistors - 47R / 150W',
        schematicLabel: '12R3',
        itemNumber: null,
      },
      {
        id: 107,
        name: 'Varistor - MVR 0.44-10',
        schematicLabel: '12R5',
        itemNumber: null,
      },
      {
        id: 108,
        name: 'Varistor - MVR 0.44-10',
        schematicLabel: '12R6',
        itemNumber: null,
      },
      {
        id: 109,
        name: 'Varistor - MVR 0.44-10',
        schematicLabel: '12R7',
        itemNumber: null,
      },
      {
        id: 110,
        name: 'Current sensor - LTC 1000-SF',
        schematicLabel: '12T1',
        itemNumber: null,
      },
      {
        id: 111,
        name: 'Current sensor - LTC 1000-SF',
        schematicLabel: '12T3',
        itemNumber: null,
      },
      {
        id: 112,
        name: 'RC-Snubber device - RCS20',
        schematicLabel: '25A1',
        itemNumber: null,
      },
      {
        id: 113,
        name: 'RC-Snubber device - RCS20',
        schematicLabel: '25A3',
        itemNumber: null,
      },
      {
        id: 114,
        name: 'Stand-by control device - SUPR13 V1.3 Rev01',
        schematicLabel: '25A2',
        itemNumber: null,
      },
      {
        id: 115,
        name: 'Mains Contactor - DILH1400/22(RAW250)',
        schematicLabel: '25K1',
        itemNumber: null,
      },
      {
        id: 116,
        name: 'Relay - iCT 25A 2NO 230/240Vac',
        schematicLabel: '25K2',
        itemNumber: null,
      },
      {
        id: 117,
        name: 'PKZM 01 Motor-Protective - Motorschutzschalter 3-pole 0.63-1.0A',
        schematicLabel: '25Q1',
        itemNumber: null,
      },
      {
        id: 118,
        name: 'Surge arrester - VAL-MS 230/3+1 FM',
        schematicLabel: '25R1',
        itemNumber: null,
      },
      {
        id: 119,
        name: 'Toggle Switches - on - on',
        schematicLabel: '25S3',
        itemNumber: null,
      },
      {
        id: 120,
        name: 'Transformer - 2kVA',
        schematicLabel: '25T1',
        itemNumber: null,
      },
      {
        id: 121,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X1',
        itemNumber: null,
      },
      {
        id: 122,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X2',
        itemNumber: null,
      },
      {
        id: 123,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X3',
        itemNumber: null,
      },
      {
        id: 124,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X10',
        itemNumber: null,
      },
      {
        id: 125,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X12',
        itemNumber: null,
      },
      {
        id: 126,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X16',
        itemNumber: null,
      },
      {
        id: 127,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X21',
        itemNumber: null,
      },
      {
        id: 128,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X22',
        itemNumber: null,
      },
      {
        id: 129,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '25X23',
        itemNumber: null,
      },
      {
        id: 130,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X1',
        itemNumber: null,
      },
      {
        id: 131,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X2',
        itemNumber: null,
      },
      {
        id: 132,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X3',
        itemNumber: null,
      },
      {
        id: 133,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X4',
        itemNumber: null,
      },
      {
        id: 134,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X5',
        itemNumber: null,
      },
      {
        id: 135,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X6',
        itemNumber: null,
      },
      {
        id: 136,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X7',
        itemNumber: null,
      },
      {
        id: 137,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X8',
        itemNumber: null,
      },
      {
        id: 138,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X9',
        itemNumber: null,
      },
      {
        id: 139,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '28X10',
        itemNumber: null,
      },
      {
        id: 140,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X2',
        itemNumber: null,
      },
      {
        id: 141,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X3',
        itemNumber: null,
      },
      {
        id: 142,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X5',
        itemNumber: null,
      },
      {
        id: 143,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X6',
        itemNumber: null,
      },
      {
        id: 144,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X8',
        itemNumber: null,
      },
      {
        id: 145,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X9',
        itemNumber: null,
      },
      {
        id: 146,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X11',
        itemNumber: null,
      },
      {
        id: 147,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X12',
        itemNumber: null,
      },
      {
        id: 148,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X14',
        itemNumber: null,
      },
      {
        id: 149,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X15',
        itemNumber: null,
      },
      {
        id: 150,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X17',
        itemNumber: null,
      },
      {
        id: 151,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X18',
        itemNumber: null,
      },
      {
        id: 152,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '40X24',
        itemNumber: null,
      },
      {
        id: 153,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '48X1',
        itemNumber: null,
      },
      {
        id: 154,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '48X2',
        itemNumber: null,
      },
      {
        id: 155,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '48X3',
        itemNumber: null,
      },
      {
        id: 156,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X4',
        itemNumber: null,
      },
      {
        id: 157,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X5',
        itemNumber: null,
      },
      {
        id: 158,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X6',
        itemNumber: null,
      },
      {
        id: 159,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X8',
        itemNumber: null,
      },
      {
        id: 160,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X9',
        itemNumber: null,
      },
      {
        id: 161,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X10',
        itemNumber: null,
      },
      {
        id: 162,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X12',
        itemNumber: null,
      },
      {
        id: 163,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '49X13',
        itemNumber: null,
      },
      {
        id: 164,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X3',
        itemNumber: null,
      },
      {
        id: 165,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X4',
        itemNumber: null,
      },
      {
        id: 166,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X5',
        itemNumber: null,
      },
      {
        id: 167,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X6',
        itemNumber: null,
      },
      {
        id: 168,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X7',
        itemNumber: null,
      },
      {
        id: 169,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '51X8',
        itemNumber: null,
      },
      {
        id: 170,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '60X1',
        itemNumber: null,
      },
      {
        id: 171,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '60X2',
        itemNumber: null,
      },
      {
        id: 172,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '60X3',
        itemNumber: null,
      },
      {
        id: 173,
        name: 'Wire terminal grey/black - STTB 2.5-PV',
        schematicLabel: '60X5',
        itemNumber: null,
      },
      {
        id: 174,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X4',
        itemNumber: null,
      },
      {
        id: 175,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X11',
        itemNumber: null,
      },
      {
        id: 176,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X13',
        itemNumber: null,
      },
      {
        id: 177,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X14',
        itemNumber: null,
      },
      {
        id: 178,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X15',
        itemNumber: null,
      },
      {
        id: 179,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X17',
        itemNumber: null,
      },
      {
        id: 180,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X18',
        itemNumber: null,
      },
      {
        id: 181,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X19',
        itemNumber: null,
      },
      {
        id: 182,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '25X24',
        itemNumber: null,
      },
      {
        id: 183,
        name: 'Wire terminal blue/black - STTB 2.5-PV BU',
        schematicLabel: '60X4',
        itemNumber: null,
      },
      {
        id: 184,
        name: 'Wire terminal PE - STTB 2.5-PE',
        schematicLabel: '25X5',
        itemNumber: null,
      },
      {
        id: 185,
        name: 'Wire terminal PE - STTB 2.5-PE',
        schematicLabel: '25X6',
        itemNumber: null,
      },
      {
        id: 186,
        name: 'Wire terminal PE - STTB 2.5-PE',
        schematicLabel: '48X4',
        itemNumber: null,
      },
      {
        id: 187,
        name: 'Wire terminal PE - STTB 2.5-PE',
        schematicLabel: '49X7',
        itemNumber: null,
      },
      {
        id: 188,
        name: 'Wire terminal PE - STTB 2.5-PE',
        schematicLabel: '3x PE',
        itemNumber: null,
      },
      {
        id: 189,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '25X7',
        itemNumber: null,
      },
      {
        id: 190,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '25X8',
        itemNumber: null,
      },
      {
        id: 191,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '25X20',
        itemNumber: null,
      },
      {
        id: 192,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X1',
        itemNumber: null,
      },
      {
        id: 193,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X4',
        itemNumber: null,
      },
      {
        id: 194,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X7',
        itemNumber: null,
      },
      {
        id: 195,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X10',
        itemNumber: null,
      },
      {
        id: 196,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X13',
        itemNumber: null,
      },
      {
        id: 197,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X16',
        itemNumber: null,
      },
      {
        id: 198,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X22',
        itemNumber: null,
      },
      {
        id: 199,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X23',
        itemNumber: null,
      },
      {
        id: 200,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X25',
        itemNumber: null,
      },
      {
        id: 201,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '40X26',
        itemNumber: null,
      },
      {
        id: 202,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '48X5',
        itemNumber: null,
      },
      {
        id: 203,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '49X1',
        itemNumber: null,
      },
      {
        id: 204,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '49X2',
        itemNumber: null,
      },
      {
        id: 205,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '49X3',
        itemNumber: null,
      },
      {
        id: 206,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '49X11',
        itemNumber: null,
      },
      {
        id: 207,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X13',
        itemNumber: null,
      },
      {
        id: 208,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X14',
        itemNumber: null,
      },
      {
        id: 209,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X15',
        itemNumber: null,
      },
      {
        id: 210,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X16',
        itemNumber: null,
      },
      {
        id: 211,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X17',
        itemNumber: null,
      },
      {
        id: 212,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X18',
        itemNumber: null,
      },
      {
        id: 213,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X19',
        itemNumber: null,
      },
      {
        id: 214,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X20',
        itemNumber: null,
      },
      {
        id: 215,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X21',
        itemNumber: null,
      },
      {
        id: 216,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X22',
        itemNumber: null,
      },
      {
        id: 217,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X23',
        itemNumber: null,
      },
      {
        id: 218,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '50X24',
        itemNumber: null,
      },
      {
        id: 219,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '51X1',
        itemNumber: null,
      },
      {
        id: 220,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '61X5',
        itemNumber: null,
      },
      {
        id: 221,
        name: 'Wire terminal grey - STTB 2.5',
        schematicLabel: '61X6',
        itemNumber: null,
      },
      {
        id: 222,
        name: 'EMC Filter - 3AYO1',
        schematicLabel: '25Z1',
        itemNumber: null,
      },
      {
        id: 223,
        name: 'Power supply - TRIO-PS/1AC/24DC/2.5',
        schematicLabel: '27G1',
        itemNumber: null,
      },
      {
        id: 224,
        name: 'Power supply - MINI-PS-100-240AC/2X15DC/1',
        schematicLabel: '27G2',
        itemNumber: null,
      },
      {
        id: 225,
        name: 'Power supply - MINI-PS-100-240AC/ 5DC/3',
        schematicLabel: '27G3',
        itemNumber: null,
      },
      {
        id: 226,
        name: 'Power supply - Quint-PS-1AC/24DC/3.5',
        schematicLabel: '27G5',
        itemNumber: null,
      },
      {
        id: 227,
        name: 'Power supply - QUINT-PS-100-240AC/24DC/10',
        schematicLabel: '27G6',
        itemNumber: null,
      },
      {
        id: 228,
        name: 'Power supply - STEP-PS/1AC/24DC/0.75',
        schematicLabel: '27G7',
        itemNumber: null,
      },
      {
        id: 229,
        name: 'Smoke Detector - ST-P-DA-24VR',
        schematicLabel: '28A1',
        itemNumber: null,
      },
      {
        id: 230,
        name: 'Capacitor for fan 2GDS25 - 4uF',
        schematicLabel: '28C1',
        itemNumber: null,
      },
      {
        id: 231,
        name: 'Capacitor for fan 2GDS25 - 4uF',
        schematicLabel: '28C2',
        itemNumber: null,
      },
      {
        id: 232,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '28K1',
        itemNumber: null,
      },
      {
        id: 233,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '28K4',
        itemNumber: null,
      },
      {
        id: 234,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '28K5',
        itemNumber: null,
      },
      {
        id: 235,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '28K6',
        itemNumber: null,
      },
      {
        id: 236,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '28K8',
        itemNumber: null,
      },
      {
        id: 237,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '40K1',
        itemNumber: null,
      },
      {
        id: 238,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '40K4',
        itemNumber: null,
      },
      {
        id: 239,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '40K5',
        itemNumber: null,
      },
      {
        id: 240,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '40K11',
        itemNumber: null,
      },
      {
        id: 241,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '48K1',
        itemNumber: null,
      },
      {
        id: 242,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '49K2',
        itemNumber: null,
      },
      {
        id: 243,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '49K3',
        itemNumber: null,
      },
      {
        id: 244,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '50K1',
        itemNumber: null,
      },
      {
        id: 245,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '50K2',
        itemNumber: null,
      },
      {
        id: 246,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '61K5',
        itemNumber: null,
      },
      {
        id: 247,
        name: 'Relay - WAGO 859-304',
        schematicLabel: '61K6',
        itemNumber: null,
      },
      {
        id: 248,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '28K1',
        itemNumber: null,
      },
      {
        id: 249,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '28K4',
        itemNumber: null,
      },
      {
        id: 250,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '28K5',
        itemNumber: null,
      },
      {
        id: 251,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '28K6',
        itemNumber: null,
      },
      {
        id: 252,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '28K8',
        itemNumber: null,
      },
      {
        id: 253,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '40K1',
        itemNumber: null,
      },
      {
        id: 254,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '40K4',
        itemNumber: null,
      },
      {
        id: 255,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '40K5',
        itemNumber: null,
      },
      {
        id: 256,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '40K11',
        itemNumber: null,
      },
      {
        id: 257,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '48K1',
        itemNumber: null,
      },
      {
        id: 258,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '49K2',
        itemNumber: null,
      },
      {
        id: 259,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '49K3',
        itemNumber: null,
      },
      {
        id: 260,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '50K1',
        itemNumber: null,
      },
      {
        id: 261,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '50K2',
        itemNumber: null,
      },
      {
        id: 262,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '61K5',
        itemNumber: null,
      },
      {
        id: 263,
        name: 'Push-In type jumper bar - LT.GRY 3WAY',
        schematicLabel: '61K6',
        itemNumber: null,
      },
      {
        id: 264,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '28K1',
        itemNumber: null,
      },
      {
        id: 265,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '28K4',
        itemNumber: null,
      },
      {
        id: 266,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '28K5',
        itemNumber: null,
      },
      {
        id: 267,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '28K6',
        itemNumber: null,
      },
      {
        id: 268,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '28K8',
        itemNumber: null,
      },
      {
        id: 269,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '40K1',
        itemNumber: null,
      },
      {
        id: 270,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '40K4',
        itemNumber: null,
      },
      {
        id: 271,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '40K5',
        itemNumber: null,
      },
      {
        id: 272,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '40K11',
        itemNumber: null,
      },
      {
        id: 273,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '48K1',
        itemNumber: null,
      },
      {
        id: 274,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '49K2',
        itemNumber: null,
      },
      {
        id: 275,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '49K3',
        itemNumber: null,
      },
      {
        id: 276,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '50K1',
        itemNumber: null,
      },
      {
        id: 277,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '50K2',
        itemNumber: null,
      },
      {
        id: 278,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '61K5',
        itemNumber: null,
      },
      {
        id: 279,
        name: 'Push-In type jumper bar - LT.GRY 4WAY',
        schematicLabel: '61K6',
        itemNumber: null,
      },
      {
        id: 280,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '28K1',
        itemNumber: null,
      },
      {
        id: 281,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '28K4',
        itemNumber: null,
      },
      {
        id: 282,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '28K5',
        itemNumber: null,
      },
      {
        id: 283,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '28K6',
        itemNumber: null,
      },
      {
        id: 284,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '28K8',
        itemNumber: null,
      },
      {
        id: 285,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '40K1',
        itemNumber: null,
      },
      {
        id: 286,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '40K4',
        itemNumber: null,
      },
      {
        id: 287,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '40K5',
        itemNumber: null,
      },
      {
        id: 288,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '40K11',
        itemNumber: null,
      },
      {
        id: 289,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '48K1',
        itemNumber: null,
      },
      {
        id: 290,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '49K2',
        itemNumber: null,
      },
      {
        id: 291,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '49K3',
        itemNumber: null,
      },
      {
        id: 292,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '50K1',
        itemNumber: null,
      },
      {
        id: 293,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '50K2',
        itemNumber: null,
      },
      {
        id: 294,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '61K5',
        itemNumber: null,
      },
      {
        id: 295,
        name: 'Push-In type jumper bar - LT.GRY 5WAY',
        schematicLabel: '61K6',
        itemNumber: null,
      },
      {
        id: 296,
        name: 'Relay cover - 859',
        schematicLabel: '28K1',
        itemNumber: null,
      },
      {
        id: 297,
        name: 'Relay cover - 859',
        schematicLabel: '28K4',
        itemNumber: null,
      },
      {
        id: 298,
        name: 'Relay cover - 859',
        schematicLabel: '28K5',
        itemNumber: null,
      },
      {
        id: 299,
        name: 'Relay cover - 859',
        schematicLabel: '28K6',
        itemNumber: null,
      },
      {
        id: 300,
        name: 'Relay cover - 859',
        schematicLabel: '28K8',
        itemNumber: null,
      },
      {
        id: 301,
        name: 'Relay cover - 859',
        schematicLabel: '40K1',
        itemNumber: null,
      },
      {
        id: 302,
        name: 'Relay cover - 859',
        schematicLabel: '40K4',
        itemNumber: null,
      },
      {
        id: 303,
        name: 'Relay cover - 859',
        schematicLabel: '40K5',
        itemNumber: null,
      },
      {
        id: 304,
        name: 'Relay cover - 859',
        schematicLabel: '40K11',
        itemNumber: null,
      },
      {
        id: 305,
        name: 'Relay cover - 859',
        schematicLabel: '48K1',
        itemNumber: null,
      },
      {
        id: 306,
        name: 'Relay cover - 859',
        schematicLabel: '49K2',
        itemNumber: null,
      },
      {
        id: 307,
        name: 'Relay cover - 859',
        schematicLabel: '49K3',
        itemNumber: null,
      },
      {
        id: 308,
        name: 'Relay cover - 859',
        schematicLabel: '50K1',
        itemNumber: null,
      },
      {
        id: 309,
        name: 'Relay cover - 859',
        schematicLabel: '50K2',
        itemNumber: null,
      },
      {
        id: 310,
        name: 'Relay cover - 859',
        schematicLabel: '61K5',
        itemNumber: null,
      },
      {
        id: 311,
        name: 'Relay cover - 859',
        schematicLabel: '61K6',
        itemNumber: null,
      },
      {
        id: 312,
        name: 'Fan with filter - LV300 with P15/350S',
        schematicLabel: '28M1',
        itemNumber: null,
      },
      {
        id: 313,
        name: 'Fan - 2GDS25  133X190R',
        schematicLabel: '28M2',
        itemNumber: null,
      },
      {
        id: 314,
        name: 'Fan - 2GDS25  133X190R',
        schematicLabel: '28M3',
        itemNumber: null,
      },
      {
        id: 315,
        name: 'Interface board - IPC2.35 R02',
        schematicLabel: '40A1',
        itemNumber: null,
      },
      {
        id: 316,
        name: 'Display board - DIPC V2.2 Rev.0',
        schematicLabel: '40A1',
        itemNumber: null,
      },
      {
        id: 317,
        name: 'Controller board - CTR651 V6.51 Rev.0',
        schematicLabel: '40A1',
        itemNumber: null,
      },
      {
        id: 318,
        name: 'INPUT/OUTPUT Expander - UFI2IO V2.00 R00',
        schematicLabel: '40A1',
        itemNumber: null,
      },
      {
        id: 319,
        name: 'Visualization panel - MT607i',
        schematicLabel: '40A2',
        itemNumber: null,
      },
      {
        id: 320,
        name: 'Connector - 165X02689XE',
        schematicLabel: '40A2',
        itemNumber: null,
      },
      {
        id: 321,
        name: 'DSUB connector female - DB9PF',
        schematicLabel: '40A2',
        itemNumber: null,
      },
      {
        id: 322,
        name: 'DSUB connector male - DB9PM',
        schematicLabel: '40A2',
        itemNumber: null,
      },
      {
        id: 323,
        name: 'Connector - HDB9P',
        schematicLabel: '40A2',
        itemNumber: null,
      },
      {
        id: 324,
        name: 'Temperature transducer - UL-200-NC',
        schematicLabel: '40A3',
        itemNumber: null,
      },
      {
        id: 325,
        name: 'Analog multiplexer 3 inputs - AMX302 R02',
        schematicLabel: '40A8',
        itemNumber: null,
      },
      {
        id: 326,
        name: 'TSA V1.00 R00 - Thermo switch adapter',
        schematicLabel: '40A9',
        itemNumber: null,
      },
      {
        id: 327,
        name: 'Safety relay - PSR-SCF- 24UC/URM/2X21',
        schematicLabel: '40K2',
        itemNumber: null,
      },
      {
        id: 328,
        name: 'Safety relay - PSR-SCF- 24UC/URM/2X21',
        schematicLabel: '40K7',
        itemNumber: null,
      },
      {
        id: 329,
        name: 'Safety relay - PSR-SCF- 24UC/URM/2X21',
        schematicLabel: '40K10',
        itemNumber: null,
      },
      {
        id: 330,
        name: 'Relay - EMG 17-REL/KSR-G 24/SO38 BK',
        schematicLabel: '40K6',
        itemNumber: null,
      },
      {
        id: 331,
        name: 'Emergency stop button - 704.064.2',
        schematicLabel: '40S1',
        itemNumber: null,
      },
      {
        id: 332,
        name: 'Emergency stop carrier - 704.950.5',
        schematicLabel: '40S1',
        itemNumber: null,
      },
      {
        id: 333,
        name: 'Emergency stop contact - 704.912.4',
        schematicLabel: '40S1',
        itemNumber: null,
      },
      {
        id: 334,
        name: 'Emergency stop label - 704.963.1',
        schematicLabel: '40S1',
        itemNumber: null,
      },
      {
        id: 335,
        name: 'Door switch - SZ 4127.000',
        schematicLabel: '40S2',
        itemNumber: null,
      },
      {
        id: 336,
        name: 'Duo Color Lamp - DCL100',
        schematicLabel: '40S4',
        itemNumber: null,
      },
      {
        id: 337,
        name: 'Selector switch - IP66',
        schematicLabel: '40S5',
        itemNumber: null,
      },
      {
        id: 338,
        name: 'Label - Start-Stop',
        schematicLabel: '40S5',
        itemNumber: null,
      },
      {
        id: 339,
        name: 'Contact block - 800F-X10',
        schematicLabel: '40S5',
        itemNumber: null,
      },
      {
        id: 340,
        name: 'Mounting latch - 800F-ALM',
        schematicLabel: '40S5',
        itemNumber: null,
      },
      {
        id: 341,
        name: 'Termostat  70°C - 70°C',
        schematicLabel: '40S7',
        itemNumber: null,
      },
      {
        id: 342,
        name: 'Lan Socket RJ45/RJ45 - IE-XM-RJ45/RJ45',
        schematicLabel: '49A1',
        itemNumber: null,
      },
      {
        id: 343,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K1',
        itemNumber: null,
      },
      {
        id: 344,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K2',
        itemNumber: null,
      },
      {
        id: 345,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K3',
        itemNumber: null,
      },
      {
        id: 346,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K4',
        itemNumber: null,
      },
      {
        id: 347,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K5',
        itemNumber: null,
      },
      {
        id: 348,
        name: 'PV contactors - LEV200H5ANA P/N',
        schematicLabel: '51K6',
        itemNumber: null,
      },
      {
        id: 349,
        name: 'Varistor - VCR10D',
        schematicLabel: '51RV1',
        itemNumber: null,
      },
      {
        id: 350,
        name: 'Varistor - VCR10D',
        schematicLabel: '51RV2',
        itemNumber: null,
      },
      {
        id: 351,
        name: 'Varistor - VCR10D',
        schematicLabel: '51RV3',
        itemNumber: null,
      },
      {
        id: 352,
        name: 'Connector - UMSTBVK 2.5/8-G-5.08',
        schematicLabel: '63X1',
        itemNumber: null,
      },
      {
        id: 353,
        name: 'Fan - 2GDS15 133X190R',
        schematicLabel: '87X3',
        itemNumber: null,
      },
    ],
    files: ['/res/schemas/SOLO500-Decorated-cf2f255.svg'],
  },
  {
    id: 2,
    description: 'SOLO 500',
    name: 'ISC-33-114-V1.02-R00',
    version: '1.02',
    status: 'production',
    dateModified: '2012-05-28',
    materials: [
      {
        id: 2,
        name: 'CONTACTOR 400VAC 9A 230VAC NO A 9-30-10',
        schematicLabel: '25K2',
        itemNumber: '1297',
      },
      {
        id: 3,
        name: 'CONTACTOR 400VAC 9A 230VAC NO A 9-30-10',
        schematicLabel: '25K3',
        itemNumber: '1297',
      },
      {
        id: 4,
        name: 'CONTACTOR 300VAC 11A Siemens',
        schematicLabel: '25K2',
        itemNumber: '42',
      },
    ],
    files: ['/res/schemas/SOLO500-Decorated-cf2f255.svg'],
  },
  {
    id: 3,
    description: 'SOLO 250 - 3',
    name: 'ISC-40-3x22-V1.00-R08',
    version: '1.08',
    status: 'production',
    dateModified: '2011-03-08',
    materials: [],
    files: ['/res/schemas/SOLO250-Decorated-cf2f255.svg'],
  },
  {
    id: 4,
    description: 'ICC',
    name: 'ICC-V1.04-R01',
    version: '1.04',
    status: 'as build',
    dateModified: '2011-11-09',
    materials: [],
    files: ['/res/schemas/SOLO250-Decorated-cf2f255.svg'],
  },
];
