ALTER TABLE cms_clients
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE cms_plants
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE cms_devices
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
