import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';
import { PercentageSummaryViewData } from '../../../shared/percentage-summary-view/models';
import { PercentageSummaryViewComponent } from '../../../shared/percentage-summary-view/percentage-summary-view.component';

@Component({
  selector: 'app-percentage-summary-test',
  imports: [PercentageSummaryViewComponent],
  templateUrl: './percentage-summary-test.component.html',
  styleUrl: './percentage-summary-test.component.less',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PercentageSummaryTestComponent {
  testData: PercentageSummaryViewData = {
    total: {
      text: 'Consumed by appliances',
      value: 54.09,
      unit: 'kWh',
      color: '#000000',
    },
    parts: [
      {
        text: 'From PV',
        value: 4.63,
        unit: 'kWh',
        color: '#ff9e13',
      },
      {
        text: 'From grid',
        value: 49.46,
        unit: 'kWh',
        color: '#8460af',
      },
    ],
  };

  testData2: PercentageSummaryViewData = {
    total: {
      text: 'Generated by PV',
      value: 4.63,
      unit: 'kWh',
      color: '#000000',
    },
    parts: [
      {
        text: 'Consumed',
        value: 4.63,
        unit: 'kWh',
        color: '#faad14',
      },
      {
        text: 'Fed to grid',
        value: 0,
        unit: 'kWh',
        color: '#8460af',
      },
    ],
  };
}
